# .goreleaser.yml

builds:
  # You can have multiple builds defined as a yaml list
  - id: "github.com/acepero13/cloud-client-go"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
